package proyectoFinalG1.Vistas;

import javax.swing.JOptionPane;
import proyectoFinalG1.Data.Conexion;
import proyectoFinalG1.Data.InquilinoData;
import proyectoFinalG1.Data.Validacion;
import proyectoFinalG1.Modelos.Inquilino;

/**
 *
 * @author Grupo 1
 */
public class NuevoInquilino extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevoInquilino
     */
    private InquilinoData id;
    private Validacion vd;
    
    public NuevoInquilino(Conexion conexion) {
        initComponents();
        inhabilitar();
        jBGuardarCambios.setEnabled(false);
        id = new InquilinoData(conexion);
        vd = new Validacion();
    }
    
    private void limpiar(){
        jTxtNombre.setText("");  
        jTxtApellido.setText("");  
        jTxtCuil.setText("");
        jTxtTrabajo.setText(""); 
        jTxtGaranteN.setText(""); 
        jTxtGaranteDni.setText("");
        jTxtId.setText("");
    }
    
    private void habilitar(){
        jTxtNombre.setEnabled(true);  
        jTxtApellido.setEnabled(true);  
        jTxtTrabajo.setEnabled(true);
        jTxtGaranteN.setEnabled(true);   
        jTxtGaranteDni.setEnabled(true);        
        jBGuardar.setEnabled(true);
        jButton5.setEnabled(true);
    }

    private void inhabilitar(){
        jTxtNombre.setEnabled(false);  
        jTxtApellido.setEnabled(false);  
        jTxtTrabajo.setEnabled(false);
        jTxtGaranteN.setEnabled(false);   
        jTxtGaranteDni.setEnabled(false);
        jBGuardar.setEnabled(false);
        jButton5.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtApellido = new javax.swing.JTextField();
        jTxtCuil = new javax.swing.JTextField();
        jTxtTrabajo = new javax.swing.JTextField();
        jTxtGaranteN = new javax.swing.JTextField();
        jTxtGaranteDni = new javax.swing.JTextField();
        jBtnNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBGuardarCambios = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jBtnBuscarXCuil = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jTxtId = new javax.swing.JTextField();
        jBBuscarXCodigo = new javax.swing.JButton();
        jBtnNuevo1 = new javax.swing.JButton();

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Buscar Propiedad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion de Inquilinos");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("CUIT");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Lugar de Trabajo");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Nombre del Garante");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("DNI del Garante");

        jTxtNombre.setBackground(new java.awt.Color(204, 204, 204));
        jTxtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTxtApellido.setBackground(new java.awt.Color(204, 204, 204));
        jTxtApellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTxtCuil.setBackground(new java.awt.Color(204, 204, 204));
        jTxtCuil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtCuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCuilActionPerformed(evt);
            }
        });

        jTxtTrabajo.setBackground(new java.awt.Color(204, 204, 204));
        jTxtTrabajo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTrabajoActionPerformed(evt);
            }
        });

        jTxtGaranteN.setBackground(new java.awt.Color(204, 204, 204));
        jTxtGaranteN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTxtGaranteN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtGaranteNActionPerformed(evt);
            }
        });

        jTxtGaranteDni.setBackground(new java.awt.Color(204, 204, 204));
        jTxtGaranteDni.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jBtnNuevo.setBackground(new java.awt.Color(204, 204, 255));
        jBtnNuevo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnNuevo.setText("Nuevo Inquilino");
        jBtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevoActionPerformed(evt);
            }
        });

        jBGuardar.setBackground(new java.awt.Color(204, 204, 255));
        jBGuardar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBGuardarCambios.setBackground(new java.awt.Color(204, 204, 255));
        jBGuardarCambios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBGuardarCambios.setText("Guardar cambios");
        jBGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarCambiosActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setText("Borrar Inquilino");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jBtnBuscarXCuil.setBackground(new java.awt.Color(204, 204, 255));
        jBtnBuscarXCuil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnBuscarXCuil.setText("Buscar Inquilino Por CUIT");
        jBtnBuscarXCuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarXCuilActionPerformed(evt);
            }
        });

        jToggleButton1.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButton1.setText("Salir");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Codigo del Inquilino");

        jTxtId.setBackground(new java.awt.Color(204, 204, 204));
        jTxtId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jBBuscarXCodigo.setBackground(new java.awt.Color(204, 204, 255));
        jBBuscarXCodigo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBBuscarXCodigo.setText("Buscar Por Codigo");
        jBBuscarXCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarXCodigoActionPerformed(evt);
            }
        });

        jBtnNuevo1.setBackground(new java.awt.Color(204, 204, 255));
        jBtnNuevo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnNuevo1.setText("Editar datos de Inquilino");
        jBtnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNuevo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtGaranteN)
                    .addComponent(jTxtApellido)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addComponent(jTxtCuil)
                    .addComponent(jTxtTrabajo))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnBuscarXCuil)
                    .addComponent(jBtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnNuevo1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTxtId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtGaranteDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jBBuscarXCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jBtnNuevo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBtnNuevo1)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscarXCuil))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGaranteN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGaranteDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarXCodigo))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jBGuardar)
                    .addComponent(jBGuardarCambios))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTxtCuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCuilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCuilActionPerformed

    private void jTxtTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTrabajoActionPerformed

    private void jTxtGaranteNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtGaranteNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtGaranteNActionPerformed

    private void jBtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        jBtnNuevo1.setEnabled(false);
        //jBtnBuscarXCuil.setEnabled(false);
        jTxtId.setEnabled(false);
        //jBBuscarXCodigo.setEnabled(false);
        jButton5.setEnabled(false);jBGuardarCambios.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_jBtnNuevoActionPerformed

    private void jBtnBuscarXCuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarXCuilActionPerformed
        // TODO add your handling code here:
        try{
            Inquilino in=id.obetenerInquilinoPorCuil(Long.parseLong(jTxtCuil.getText()));
            jTxtNombre.setText(in.getNombre());  
        jTxtApellido.setText(in.getApellido());  
        jTxtTrabajo.setText(in.getTrabajo()); 
        jTxtGaranteN.setText(in.getGarante()); 
        jTxtGaranteDni.setText(in.getDniGarante()+""); 
        jTxtId.setText(in.getIdInquilino()+"");
        habilitar();
        jBGuardar.setEnabled(false);jBGuardarCambios.setEnabled(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Debe cargar un Cuit valido para buscar un Inquilino");
        }
        
    }//GEN-LAST:event_jBtnBuscarXCuilActionPerformed
private boolean validarCampos(){
        boolean valido = true;
        if(!vd.EsPalabra(jTxtNombre.getText())){
            valido=false;
        }
        if(!vd.EsPalabra(jTxtApellido.getText())){
            valido=false;
        }
        if(!vd.ValidarDni(Integer.parseInt(jTxtCuil.getText()))){
            valido=false;
        }
        if(vd.EstaVacio(jTxtTrabajo.getText())){
            valido=false;
        }
        if(!vd.ValidarNumerosEnteros(Integer.parseInt(jTxtGaranteDni.getText()))){
            valido=false;
        }
        if(!vd.EsPalabra(jTxtGaranteN.getText())){
            valido=false;
        }
        
        return valido;
    }
    private void jBGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarCambiosActionPerformed
        // TODO add your handling code here:
        habilitar();
        try {
            String nombre = jTxtNombre.getText();
            String apellido = jTxtApellido.getText();
            int cuil = Integer.parseInt(jTxtCuil.getText());
            String trabajo = jTxtTrabajo.getText();
            String garante = jTxtGaranteN.getText();
            int garanteDni = Integer.parseInt(jTxtGaranteDni.getText());
            int iD = Integer.parseInt(jTxtId.getText());
            if(validarCampos()){
               Inquilino in = new Inquilino(iD, nombre,apellido, cuil, trabajo, garante, garanteDni, true);
                if(id.modificarInquilino(in)){
                    JOptionPane.showMessageDialog(this, "El inquilino se actualizo con exito");
                }else{
                    JOptionPane.showMessageDialog(this, "Error al actualizar inquilino");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Alguno de los campos llenados contiene informacion invalida o no contiene nada");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar Inquilino");
        }
    }//GEN-LAST:event_jBGuardarCambiosActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        try{
            Inquilino in=new Inquilino();
            String nombre=jTxtNombre.getText();  
        String apellido =jTxtApellido.getText();  
        String trabajo=jTxtTrabajo.getText(); 
        String garante =jTxtGaranteN.getText(); 
        int dniGarante =Integer.parseInt(jTxtGaranteDni.getText()); 
        long cuil = Long.parseLong(jTxtCuil.getText());
        in.setNombre(nombre);
        in.setApellido(apellido);
        in.setCuil(cuil);
        in.setActivo(true);
        in.setTrabajo(trabajo);
        in.setGarante(garante);
        in.setDniGarante(dniGarante);
        if(validarCampos()){
            id.agregarInquilino(in);
        jTxtId.setText(in.getIdInquilino()+"");
        JOptionPane.showMessageDialog(this, "El Inquilino se agrego con exito");
        }else{
            JOptionPane.showMessageDialog(this, "Error, un campo contiene datos invalidos o no los contiene");
        }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error, un campo contiene datos invalidos o no los contiene");
        }
        limpiar();
        inhabilitar();
        jTxtCuil.setEnabled(true);
        jTxtId.setEnabled(true);
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            Inquilino in = id.obetenerInquilinoPorCuil(Long.parseLong(jTxtCuil.getText()));
            id.borrarInquilino(in.getIdInquilino());
            limpiar();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Debe cargar un Cuit valido para buscar un Inquilino");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBBuscarXCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarXCodigoActionPerformed
        // TODO add your handling code here:
        try{
            Inquilino in=id.obetenerInquilinoPorID(Integer.parseInt(jTxtId.getText()));
            jTxtNombre.setText(in.getNombre());  
        jTxtApellido.setText(in.getApellido());  
        jTxtTrabajo.setText(in.getTrabajo()); 
        jTxtGaranteN.setText(in.getGarante()); 
        jTxtGaranteDni.setText(in.getDniGarante()+""); 
        jTxtCuil.setText(in.getCuil()+"");
        habilitar();
        jTxtId.setEnabled(true);
        jBGuardarCambios.setEnabled(true);jBGuardar.setEnabled(false);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Debe cargar un codigo valido para buscar un Inquilino");
        }
    }//GEN-LAST:event_jBBuscarXCodigoActionPerformed

    private void jBtnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNuevo1ActionPerformed
        // TODO add your handling code here:
         habilitar();
        jBtnNuevo1.setEnabled(false);
        jBtnBuscarXCuil.setEnabled(false);
        jTxtId.setEnabled(false);
        jBBuscarXCodigo.setEnabled(false);
        jButton5.setEnabled(true);
        jBGuardarCambios.setEnabled(true);
        jBGuardar.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_jBtnNuevo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarXCodigo;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBGuardarCambios;
    private javax.swing.JButton jBtnBuscarXCuil;
    private javax.swing.JButton jBtnNuevo;
    private javax.swing.JButton jBtnNuevo1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtCuil;
    private javax.swing.JTextField jTxtGaranteDni;
    private javax.swing.JTextField jTxtGaranteN;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtTrabajo;
    // End of variables declaration//GEN-END:variables
}
